Repository mlibrary/search, pull requests merged in 2022-01, with the labels that each got.

#295 SEARH-1504: Add fielded basic search box
  package-lock.json
  src/modules/affiliation/actions/index.js
  src/modules/affiliation/components/choose-affiliation.js
  src/modules/affiliation/index.js
  src/modules/affiliation/reducer/index.js
  src/modules/core/components/SearchHeader/header.js
  src/modules/core/components/SearchHeader/index.js
  src/modules/flint/components/FlintAlerts/index.js
  src/modules/getthis/components/GetThisFAQ/index.js
  src/modules/pride/components/URLSearchQueryWrapper/index.js
  src/modules/records/components/RecordFull/index.js
  src/modules/records/components/RecordList/index.js
  src/modules/search/components/SearchBox/index.js
  src/modules/search/search-options.js
Labels: Type: Enhancement

#299 [SEARCH-1564] Browse Tip Typos
  src/modules/search/search-options.js
Labels: Type: Bug

#300 [SEARCH-1571] Add tracking for search dropdown menu
  public/index.html
  src/modules/core/components/Footer/index.js
  src/modules/core/components/SearchHeader/index.js
  src/modules/search/components/SearchBox/index.js
Labels: Type: Feature
